CREATE TYPE "TimeFormat" AS ENUM ('TWELVE_HOUR', 'TWENTY_FOUR_HOUR');

ALTER TABLE "User"
ADD COLUMN "bio" TEXT,
ADD COLUMN "timeFormat" "TimeFormat" NOT NULL DEFAULT 'TWELVE_HOUR',
ADD COLUMN "allowSearchEngineIndexing" BOOLEAN NOT NULL DEFAULT false;
